name: Node.js CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
